apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test-1-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: app-test-1
  template:
    metadata:
      labels:
        app: app-test-1
    spec:
      containers:
      - name: app-test-1
        image: nginx
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-test-1-svc
  namespace: default
  labels:
    app: app-test-1
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: app-test-1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-test-1-ingress
  namespace: default
spec:
  rules:
  - host: "app.crazytechme.tk"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-test-1-svc 
            port:
              number: 80
  tls:
  - hosts:
    - app.crazytechme.tk
    secretName: app-test-1-tls-secret              
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-test-1-cert
  namespace: default
spec:
  secretName: app-test-1-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - app.crazytechme.tk
